ulan/account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [

    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),
    path('user-logout/', views.user_logout_request, name='user_logout'),
    path('masterdata_login/', views.masterdata_login, name='masterdata_login'),

]

ulan/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import (KroyListView, KroyCreateView, KroyUpdateView, KroyDetailListView, KroyDeleteView,
                    KroyDetailCreateView, KroyDetailUpdateView, MasterdataListView, masterdatauser,
                    operation_code_create, operation_code_update, operation_code_delete, KroyDetailView,
                    KroyDetailDeleteView, get_operation_codes, get_operation_list, users)
app_name = 'main'

urlpatterns = [
    #path("", views.index, name="home"),
    path("index", views.index),

    path('users/', users, name='users'),

    path('kroy/', KroyListView.as_view(), name='kroy-list'),
    path('kroy/create/', KroyCreateView.as_view(), name='kroy-create'),
    path('kroy/update/<int:pk>/', KroyUpdateView.as_view(), name='kroy-update'),
    path('kroy/delete/<int:pk>/', KroyDeleteView.as_view(), name='kroy-delete'),

    path('<int:kroy_id>/', views.KroyDetailView, name='kroy-detail-view'),
    path('kroy-detail/', KroyDetailListView.as_view(), name='kroy-detail-list'),
    path('kroy-detail/create/<int:kroy_id>', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    path('kroy-detail/update/<int:pk>/', KroyDetailUpdateView.as_view(), name='kroy-detail-update'),
    path('kroy-detail/delete/<int:pk>/', KroyDetailDeleteView.as_view(), name='kroy-detail-delete'),
    path('kroy-detail/<int:kroy_id>/', KroyDetailView, name='kroy-detail-view'),



    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),

    #path('kroy_details/new/<int:kroy_id>/', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),
    path('masterdata', MasterdataListView.as_view(), name='masterdata_list'),

    #Users page
    #path('main/masterdatauser/', views.masterdatauser_view, name='masterdatauser'),
    path('masterdatauser/', views.masterdatauser, name='masterdatauser'),
    path('get_operation_codes/', get_operation_codes, name='get_operation_codes'),
    path('get_operation_list/', get_operation_list, name='get_operation_list'),
    path('get_operation_price', views.get_operation_price, name='get_operation_price'),

    #Operations
    path('operation_code/create/', views.operation_code_create, name='operation_code_create'),
    path('operation_code/<int:pk>/update/', views.operation_code_update, name='operation_code_update'),
    path('operation_code/<int:pk>/delete/', views.operation_code_delete, name='operation_code_delete'),
    path('operation_code/', views.operation_code_list, name='operation_code_list'),

    path('operation_code/<int:operation_code_id>/operations/', views.operation_list_detail, name='operation_list_detail'),
    path('operation_code/<int:operation_code_id>/operations/create/', views.operation_list_create, name='operation_list_create'),
    path('operation_code/operations/<int:pk>/edit/', views.operation_list_update, name='operation_list_update'),
    path('operation_code/operations/<int:pk>/delete/', views.operation_list_delete, name='operation_list_delete'),
    path('operation-list/<int:operation_code_id>/', views.OperationListView, name='operation_list'),

    #kroy+operation naznachenie operatsii
    path('opercode/', views.kroy_operation_code_list, name='kroy_operation_code_list'),
    path('opercode/new/', views.kroy_operation_code_create, name='kroy_operation_code_create'),
    path('opercode/<int:pk>/edit/', views.kroy_operation_code_edit, name='kroy_operation_code_edit'),
    path('opercode/<int:pk>/delete/', views.kroy_operation_code_delete, name='kroy_operation_code_delete'),
]

ulan/reports/urls.py
from django.urls import path
from . import views
from .views import weekly_report, weekly_report_all

app_name = 'reports'
urlpatterns = [
    path("", views.index, name="home"),
    path("index", views.index),
    path('weekly-report/', weekly_report, name='weekly_report'),
    path('weekly-report-all/', weekly_report_all, name='weekly_report_all'),
    path('report/', views.alluser_report, name='alluser_report'),
]

ulan/ulan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('reports.urls')),
    path('', include(('reports.urls', 'reports'), namespace='reports')),
    path('main/', include('main.urls')),
    path('account/', include('account.urls')),
    path('material/', include('material.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('orders/', include('orders.urls')),
    path('client/', include('client.urls')),
    #path('reports/', include('reports.urls', namespace='reports')),
 #   path('login/', LoginView.as_view(), name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ulan/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import (Kroy, Kroy_detail, Operation_code, Operation_list, Kroy_operation_code, Status)
from .forms import (KroyForm, KroyDetailForm, Masterdata, MasterdataSearchForm,
                    OperationCodeForm, OperationListForm, KroyOperationCodeForm,)
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models import Sum
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse




#@permission_required('main.add_operationcode', raise_exception=True)
def index(request):
    if not request.user.is_authenticated:
        return redirect("account:login")
    return render(request, "main/index.html")

def users(request):

    return render(request, "main/mdata/users.html")

# --- Master data alani basi ---
class MasterdataListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):

    model = Masterdata
    template_name = 'main/mdata/masterdata_list.html'
    context_object_name = 'masterdata_list'
    login_url = '/account:login/'
    permission_required = 'main.view_masterdata'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_queryset(self):
        form = MasterdataSearchForm(self.request.GET)
        queryset = Masterdata.objects.filter(is_active=True)

        if form.is_valid():
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')
            #uchastok_search = form.cleaned_data.get('uchastok_search')
            kroy_no_search = form.cleaned_data.get('kroy_no_search')
            user = form.cleaned_data.get('user')

            filter_conditions = Q()

            if start_date:
                filter_conditions &= Q(created__gte=start_date)
            if end_date:
                filter_conditions &= Q(created__lte=end_date)
            if kroy_no_search:
                filter_conditions &= Q(kroy_no__icontains=kroy_no_search)
            if user:
                filter_conditions &= Q(user__username__icontains=user)

                # Apply the combined filters
            queryset = queryset.filter(filter_conditions)

        queryset = queryset.order_by('-created')
        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = MasterdataSearchForm(self.request.GET)
        context['additional_variable'] = 'Some additional value'

        return context

# --- Masterdata alani sonu ---

# --- Kroy basi ---
class KroyListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Kroy
    template_name = 'main/kroy/kroy_list.html'
    login_url = '/account:login/'
    permission_required = 'main.view_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_queryset(self):
        # Filter the Kroy objects where is_active is True
        return Kroy.objects.filter(is_active=True).order_by('-id')[:100]

class KroyCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Kroy
    form_class = KroyForm
    template_name = 'main/kroy/kroy_form.html'
    success_url = reverse_lazy ('main:kroy-create')
    login_url = '/account:login/'
    permission_required = 'app_name.view_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kroy_list'] = Kroy.objects.all().order_by('-created')[:10]  # Add this line to pass the data to the template
        return context

class KroyDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Kroy
    template_name = 'main/kroy/kroy_confirm_delete.html'
    success_url = reverse_lazy('main:kroy-list')
    login_url = '/account:login/'
    permission_required = 'app_name.delete_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')
class KroyUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Kroy
    form_class = KroyForm
    template_name = 'main/kroy/kroy_form.html'
    #success_url = '/kroy/'
    success_url = reverse_lazy('main:kroy-list')
    login_url = '/account:login/'
    permission_required = 'app_name.view_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')
# --- Kroy sonu ---
# ---Kroy detail basi ---
@login_required
@permission_required('main.add_view', raise_exception=True)
def KroyDetailView(request, kroy_id):
    if not request.user.is_authenticated:
        return redirect("account:login")

    kroy_instance = get_object_or_404(Kroy, pk=kroy_id)
    kroy_details = Kroy_detail.objects.filter(kroy=kroy_instance)
    kroy_list = Kroy.objects.all()
    kroy_operation_codes = Kroy_operation_code.objects.filter(kroy=kroy_instance).order_by('operation_code')
    # Stuk sütununun toplamını hesapla
    stuk_total = kroy_details.aggregate(stuk_sum=Sum('stuk'))['stuk_sum'] or 0
    context = {
        'objects':kroy_list,
        'kroy_instance': kroy_instance,
        'kroy_details': kroy_details,
        'kroy_operation_codes': kroy_operation_codes,  # Yeni eklenen liste
        'stuk_total': stuk_total,  # Toplamı context'e ekle
    }
    return render(request, 'main/kroy/kroy_detail_view.html', context)

class KroyDetailListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Kroy_detail
    template_name = 'main/kroy/kroy_detail_list.html'
    login_url = '/account:login/'
    permission_required = 'app_name.view_KroyDetail'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('login')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_kroys = Kroy_detail.objects.order_by('-created')[:30]  # Son 10 kaydı al
        print(latest_kroys)
        context['latest_kroys'] = latest_kroys  # Son 10 kaydı context'e ekle
        return context


class KroyDetailCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Kroy_detail
    form_class = KroyDetailForm
    template_name = 'main/kroy/kroy_detail_form.html'
    success_url = reverse_lazy('main:kroy-detail-create')
    login_url = '/login/'
    permission_required = 'app_name.view_KroyDetail'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kroy_detail_list'] = Kroy_detail.objects.all().order_by('-created')[:10]  # Add this line to pass the data to the template
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kroy_instance_id = self.kwargs.get('kroy_id')
        try:
            kroy_instance = Kroy.objects.get(pk=kroy_instance_id)
            kwargs['kroy_instance'] = kroy_instance
        except Kroy.DoesNotExist:
            raise Http404("Kroy matching query does not exist.")
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        #burada geldigim kroy-detail-view daki secilmis kroya gitmesi lazim
        return reverse_lazy('main:kroy-detail-view', kwargs={'kroy_id': self.object.kroy.pk})

class KroyDetailUpdateView(UpdateView, PermissionRequiredMixin):
    model = Kroy_detail
    form_class = KroyDetailForm
    template_name = 'main/kroy/kroy_detail_form.html'
    success_url = '/kroy-detail/'
    permission_required = 'app_name.view_KroyDetail'

    def get_success_url(self):
        #burada geldigim kroy-detail-view daki secilmis kroya gitmesi lazim
        return reverse_lazy('main:kroy-detail-view', kwargs={'kroy_id': self.object.kroy.pk})


class KroyDetailDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Kroy_detail
    template_name = 'main/kroy/kroy_detail_confirm_delete.html'
    permission_required = 'app_name.view_KroyDetail'
    #success_url = reverse_lazy('kroy-detail-view')  # Silme işleminden sonra yönlendirilecek URL

    def handle_no_permission(self):
        return redirect('account:login')

    def get_success_url(self):
        #burada geldigim kroy-detail-view daki secilmis kroya gitmesi lazim
        return reverse_lazy('main:kroy-detail-view', kwargs={'kroy_id': self.object.kroy.pk})


# ---Kroy detail sonu ---
# --- Operasynu kodu olusturma alani basi---
@login_required
@permission_required('main.add_view', raise_exception=True)
def operation_code_create(request):
    if request.method == 'POST':
        form = OperationCodeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:operation_code_list')  # operation_code_list view'ine yönlendir
    else:
        form = OperationCodeForm()
    return render(request, 'main/operation/operation_code_create.html', {'form': form})

@login_required
@permission_required('main.add_view', raise_exception=True)

ulan/main/templates/main/partials/_categories.html
{{ category.name|title }}
        <div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown link
  </a>

  <ul class="dropdown-menu">
      {% for category in categories %}
    <li>
    {% if category.slug == selected_category %}
    <a class="dropdown-item " href="{% url 'work_stations_by_category' category.slug %}">
        {{ category.name|title }}</a>
    {% else %}
    <a class="dropdown-item " href="{% url 'work_stations_by_category' category.slug %}">
        {{ category.name|title }}</a>
    {% endif %}
    </li>
{% endfor %}
  </ul>
</div>

ulan/main/templates/main/partials/_kroy_list.html
<div class="container">

         <table class="table caption-top">
  <caption>Крой Список</caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Крой №</th>
      <th scope="col">Наименование</th>
      <th scope="col">Единица</th>
      <th scope="col">Расход ткани</th>
      <th scope="col">Расхо дублерин</th>
      <th scope="col"> </th>
    </tr>
  </thead>

     <tbody>
     {% for kroy in object_list %}
     <tr>
  <th scope="row"></th>
      <td><a href="{% url 'main:kroy-detail-view' kroy.pk %}">{{ kroy.kroy_no }}</a></td>
      <td>{{ kroy.name }}</td>
      <td>{{ kroy.edinitsa }}</td>
      <td>{{ kroy.ras_tkani }}</td>
      <td>{{ kroy.ras_dublerin }}</td>
      <td><a href="{% url 'main:kroy-update' kroy.pk %}">Edit</a></td>
    </tr>
     {% empty %}
            <li>No Kroy items available</li>
        {% endfor %}
  </tbody>
</table>
</div>

ulan/main/templates/main/partials/_nav_main.html
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'reports:home' %}">T-Soft</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">

        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'reports:home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Крой</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:kroy-list' %}">Крой список</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:kroy-create' %}">Создать крой</a></li>
                       <!--<li><a class="dropdown-item" href="">Создать крой деталь</a></li> -->

                    </ul>
                </div>
            </li>
            <li class="nav-item dropdown">
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Операция</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:operation_code_list' %}">Список код операции</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:kroy_operation_code_list' %}">Назначить операцию</a></li>
                        <li>

                    </ul>
                </div>
            </li>

        </ul>
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Выход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Привет,{{ user.username }} </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:login' %}">Вход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Регистрация</a>
                </li>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

ulan/main/templates/main/partials/_work_stations_list.html
{% load static %}


<div class="row mt-2" >
        {{ work_stations.work_station|title }}
        <input type="hidden" name="work_stations" value="{{ work_stations.id }}">
        <input type="hidden" class="form-control" name="category" value="{{ work_stations.category_id }}">
        {{ work_stations.category }}
    <div class="col">
        <select name="article" class="form-control">
                <option selected>Выбирайте...</option>
                {% for article in articles %}
                <option value="{{ article.id }}" >{{ article.name }}</option>
                {% endfor %}
        </select>
    </div>
    <div class="col">
        <input type="text" class="form-control" placeholder="Количество" aria-label="" name="quantity">
    </div>
    <div class="col">
        <input type="text" class="form-control" placeholder="Примечение" aria-label="" name="description">
    </div>
    <div class="col">
        <input type="text" class="form-control" placeholder="Брак" aria-label="last name" name="brak">
    </div>
</div>

ulan/main/templates/main/partials/article-list.html
<div class="input-group mb-3">
  <select name="article" class="form-select" id="inputGroupSelect03" >
    <option selected>Choose...</option>
      {% for article in articles %}
    <option value="{{ article.id }}" >{{ article.name }}</option>
     {% endfor %}
  </select>
</div>

ulan/main/templates/main/partials/test.html
{% load static %}



<div class="row">
<div class="col">
    <form action="{% url 'createdata' %}" method="POST">{% csrf_token %}
        {{ work_stations.category|title }}
         <input type="" name="x1" value="">
          <input type="" name="x2" value="">
        <input type="submit">
    </form>
  </div>

</div>