ulan/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import (KroyListView, KroyCreateView, KroyUpdateView, KroyDetailListView, KroyDeleteView,
                    KroyDetailCreateView, KroyDetailUpdateView, MasterdataListView, masterdatauser,
                    operation_code_create, operation_code_update, operation_code_delete, KroyDetailView,
                    KroyDetailDeleteView, get_operation_codes, get_operation_list, users)
app_name = 'main'

urlpatterns = [
    #path("", views.index, name="home"),
    path("index", views.index),

    path('users/', users, name='users'),

    path('kroy/', KroyListView.as_view(), name='kroy-list'),
    path('kroy/create/', KroyCreateView.as_view(), name='kroy-create'),
    path('kroy/update/<int:pk>/', KroyUpdateView.as_view(), name='kroy-update'),
    path('kroy/delete/<int:pk>/', KroyDeleteView.as_view(), name='kroy-delete'),

    path('<int:kroy_id>/', views.KroyDetailView, name='kroy-detail-view'),
    path('kroy-detail/', KroyDetailListView.as_view(), name='kroy-detail-list'),
    path('kroy-detail/create/<int:kroy_id>', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    path('kroy-detail/update/<int:pk>/', KroyDetailUpdateView.as_view(), name='kroy-detail-update'),
    path('kroy-detail/delete/<int:pk>/', KroyDetailDeleteView.as_view(), name='kroy-detail-delete'),
    path('kroy-detail/<int:kroy_id>/', KroyDetailView, name='kroy-detail-view'),



    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),

    #path('kroy_details/new/<int:kroy_id>/', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),
    path('masterdata', MasterdataListView.as_view(), name='masterdata_list'),

    #Users page
    #path('main/masterdatauser/', views.masterdatauser_view, name='masterdatauser'),
    path('masterdatauser/', views.masterdatauser, name='masterdatauser'),
    path('get_operation_codes/', get_operation_codes, name='get_operation_codes'),
    path('get_operation_list/', get_operation_list, name='get_operation_list'),
    path('get_operation_price', views.get_operation_price, name='get_operation_price'),

    #Operations
    path('operation_code/create/', views.operation_code_create, name='operation_code_create'),
    path('operation_code/<int:pk>/update/', views.operation_code_update, name='operation_code_update'),
    path('operation_code/<int:pk>/delete/', views.operation_code_delete, name='operation_code_delete'),
    path('operation_code/', views.operation_code_list, name='operation_code_list'),

    path('operation_code/<int:operation_code_id>/operations/', views.operation_list_detail, name='operation_list_detail'),
    path('operation_code/<int:operation_code_id>/operations/create/', views.operation_list_create, name='operation_list_create'),
    path('operation_code/operations/<int:pk>/edit/', views.operation_list_update, name='operation_list_update'),
    path('operation_code/operations/<int:pk>/delete/', views.operation_list_delete, name='operation_list_delete'),
    path('operation-list/<int:operation_code_id>/', views.OperationListView, name='operation_list'),

    #kroy+operation naznachenie operatsii
    path('opercode/', views.kroy_operation_code_list, name='kroy_operation_code_list'),
    path('opercode/new/', views.kroy_operation_code_create, name='kroy_operation_code_create'),
    path('opercode/<int:pk>/edit/', views.kroy_operation_code_edit, name='kroy_operation_code_edit'),
    path('opercode/<int:pk>/delete/', views.kroy_operation_code_delete, name='kroy_operation_code_delete'),
]

ulan/ulan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('reports.urls')),
    path('', include(('reports.urls', 'reports'), namespace='reports')),
    path('main/', include('main.urls')),
    path('account/', include('account.urls')),
    path('material/', include('material.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('orders/', include('orders.urls')),
    path('client/', include('client.urls')),
    #path('reports/', include('reports.urls', namespace='reports')),
 #   path('login/', LoginView.as_view(), name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ulan/main/forms.py
from django import forms
from .models import Kroy, Kroy_detail, Masterdata, Operation_code, Operation_list, Kroy_operation_code  #, Code_operation, Kroy_operations
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

class KroyForm(forms.ModelForm):
    class Meta:
        model = Kroy
        fields = ['kroy_no', 'name', 'ras_tkani', 'ras_dublerin', 'order', 'edinitsa', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 23}),
        }

    def clean_kroy_no(self):
        kroy_no = self.cleaned_data.get('kroy_no')
        if self.instance and self.instance.pk is not None:
            return kroy_no
        if Kroy.objects.filter(kroy_no=kroy_no).exists():
            raise ValidationError("Этот номер Кроя уже существует. Пожалуйста, введите другой номер.")
        return kroy_no

class KroyDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.kroy_instance = kwargs.pop('kroy_instance', None)
        super(KroyDetailForm, self).__init__(*args, **kwargs)
        if self.kroy_instance:
            self.fields['kroy'].widget.attrs['readonly'] = True
            self.initial['kroy'] = self.kroy_instance.pk

    class Meta:
        model = Kroy_detail
        fields = ['kroy', 'pachka', 'razmer', 'rost', 'stuk', 'city', 'color','description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 23}),
        }

class MasterdataSearchForm(forms.Form):
    start_date = forms.DateField(label='Дата начала', required=False)
    end_date = forms.DateField(label='Дата окончания', required=False)
    uchastok_search = forms.CharField(label='Искать по участке', required=False)
    kroy_no_search = forms.CharField(label='Искать по крой но:', required=False)
    user = forms.CharField(label='Искать по крой но:', required=False)

class MasterdataForm(forms.ModelForm):
    class Meta:
        model = Masterdata
        fields = ['user']  # Add other fields as needed

class OperationCodeForm(forms.ModelForm):
    class Meta:
        model = Operation_code
        fields = ['title', 'description', 'product_type', 'is_active']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 23}),
        }

class OperationListForm(forms.ModelForm):
    class Meta:
        model = Operation_list
        fields = ['title', 'price']

class KroyOperationCodeForm(forms.ModelForm):
    class Meta:
        model = Kroy_operation_code
        fields = ['kroy', 'operation_code', 'is_active']
        widgets = {
            'kroy': forms.Select(attrs={'class': 'form-control'}),
            'operation_code': forms.Select(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

ulan/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import (Kroy, Kroy_detail, Operation_code, Operation_list, Kroy_operation_code, Status)
from .forms import (KroyForm, KroyDetailForm, Masterdata, MasterdataSearchForm,
                    OperationCodeForm, OperationListForm, KroyOperationCodeForm,)
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models import Sum
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse




#@permission_required('main.add_operationcode', raise_exception=True)
def index(request):
    if not request.user.is_authenticated:
        return redirect("account:login")
    return render(request, "main/index.html")

def users(request):

    return render(request, "main/mdata/users.html")

# --- Master data alani basi ---
class MasterdataListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):

    model = Masterdata
    template_name = 'main/mdata/masterdata_list.html'
    context_object_name = 'masterdata_list'
    login_url = '/account:login/'
    permission_required = 'main.view_masterdata'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_queryset(self):
        form = MasterdataSearchForm(self.request.GET)
        queryset = Masterdata.objects.filter(is_active=True)

        if form.is_valid():
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')
            #uchastok_search = form.cleaned_data.get('uchastok_search')
            kroy_no_search = form.cleaned_data.get('kroy_no_search')
            user = form.cleaned_data.get('user')

            filter_conditions = Q()

            if start_date:
                filter_conditions &= Q(created__gte=start_date)
            if end_date:
                filter_conditions &= Q(created__lte=end_date)
            if kroy_no_search:
                filter_conditions &= Q(kroy_no__icontains=kroy_no_search)
            if user:
                filter_conditions &= Q(user__username__icontains=user)

                # Apply the combined filters
            queryset = queryset.filter(filter_conditions)

        queryset = queryset.order_by('-created')
        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = MasterdataSearchForm(self.request.GET)
        context['additional_variable'] = 'Some additional value'

        return context

# --- Masterdata alani sonu ---

# --- Kroy basi ---
class KroyListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Kroy
    template_name = 'main/kroy/kroy_list.html'
    login_url = '/account:login/'
    permission_required = 'main.view_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_queryset(self):
        # Filter the Kroy objects where is_active is True
        return Kroy.objects.filter(is_active=True).order_by('-id')[:100]

class KroyCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Kroy
    form_class = KroyForm
    template_name = 'main/kroy/kroy_form.html'
    success_url = reverse_lazy ('main:kroy-create')
    login_url = '/account:login/'
    permission_required = 'app_name.view_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kroy_list'] = Kroy.objects.all().order_by('-created')[:10]  # Add this line to pass the data to the template
        return context

class KroyDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Kroy
    template_name = 'main/kroy/kroy_confirm_delete.html'
    success_url = reverse_lazy('main:kroy-list')
    login_url = '/account:login/'
    permission_required = 'app_name.delete_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')
class KroyUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Kroy
    form_class = KroyForm
    template_name = 'main/kroy/kroy_form.html'
    #success_url = '/kroy/'
    success_url = reverse_lazy('main:kroy-list')
    login_url = '/account:login/'
    permission_required = 'app_name.view_kroy'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')
# --- Kroy sonu ---
# ---Kroy detail basi ---
@login_required
@permission_required('main.add_view', raise_exception=True)
def KroyDetailView(request, kroy_id):
    if not request.user.is_authenticated:
        return redirect("account:login")

    kroy_instance = get_object_or_404(Kroy, pk=kroy_id)
    kroy_details = Kroy_detail.objects.filter(kroy=kroy_instance)
    kroy_list = Kroy.objects.all()
    kroy_operation_codes = Kroy_operation_code.objects.filter(kroy=kroy_instance).order_by('operation_code')
    # Stuk sütununun toplamını hesapla
    stuk_total = kroy_details.aggregate(stuk_sum=Sum('stuk'))['stuk_sum'] or 0
    context = {
        'objects':kroy_list,
        'kroy_instance': kroy_instance,
        'kroy_details': kroy_details,
        'kroy_operation_codes': kroy_operation_codes,  # Yeni eklenen liste
        'stuk_total': stuk_total,  # Toplamı context'e ekle
    }
    return render(request, 'main/kroy/kroy_detail_view.html', context)

class KroyDetailListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Kroy_detail
    template_name = 'main/kroy/kroy_detail_list.html'
    login_url = '/account:login/'
    permission_required = 'app_name.view_KroyDetail'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('login')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_kroys = Kroy_detail.objects.order_by('-created')[:30]  # Son 10 kaydı al
        print(latest_kroys)
        context['latest_kroys'] = latest_kroys  # Son 10 kaydı context'e ekle
        return context


class KroyDetailCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Kroy_detail
    form_class = KroyDetailForm
    template_name = 'main/kroy/kroy_detail_form.html'
    success_url = reverse_lazy('main:kroy-detail-create')
    login_url = '/login/'
    permission_required = 'app_name.view_KroyDetail'

    def handle_no_permission(self):
        # Kullanıcı oturum açmamışsa, giriş yapma sayfasına yönlendir
        return redirect('account:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kroy_detail_list'] = Kroy_detail.objects.all().order_by('-created')[:10]  # Add this line to pass the data to the template
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kroy_instance_id = self.kwargs.get('kroy_id')
        try:
            kroy_instance = Kroy.objects.get(pk=kroy_instance_id)
            kwargs['kroy_instance'] = kroy_instance
        except Kroy.DoesNotExist:
            raise Http404("Kroy matching query does not exist.")
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        #burada geldigim kroy-detail-view daki secilmis kroya gitmesi lazim
        return reverse_lazy('main:kroy-detail-view', kwargs={'kroy_id': self.object.kroy.pk})

class KroyDetailUpdateView(UpdateView, PermissionRequiredMixin):
    model = Kroy_detail
    form_class = KroyDetailForm
    template_name = 'main/kroy/kroy_detail_form.html'
    success_url = '/kroy-detail/'
    permission_required = 'app_name.view_KroyDetail'

    def get_success_url(self):
        #burada geldigim kroy-detail-view daki secilmis kroya gitmesi lazim
        return reverse_lazy('main:kroy-detail-view', kwargs={'kroy_id': self.object.kroy.pk})


class KroyDetailDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Kroy_detail
    template_name = 'main/kroy/kroy_detail_confirm_delete.html'
    permission_required = 'app_name.view_KroyDetail'
    #success_url = reverse_lazy('kroy-detail-view')  # Silme işleminden sonra yönlendirilecek URL

    def handle_no_permission(self):
        return redirect('account:login')

    def get_success_url(self):
        #burada geldigim kroy-detail-view daki secilmis kroya gitmesi lazim
        return reverse_lazy('main:kroy-detail-view', kwargs={'kroy_id': self.object.kroy.pk})


# ---Kroy detail sonu ---
# --- Operasynu kodu olusturma alani basi---
@login_required
@permission_required('main.add_view', raise_exception=True)
def operation_code_create(request):
    if request.method == 'POST':
        form = OperationCodeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:operation_code_list')  # operation_code_list view'ine yönlendir
    else:
        form = OperationCodeForm()
    return render(request, 'main/operation/operation_code_create.html', {'form': form})

@login_required
@permission_required('main.add_view', raise_exception=True)

ulan/main/templates/main/opercode/kroy_operation_code_confirm_delete.html
{% extends "main/base.html" %}

{% block content %}
<div class="container mt-2">
  <h2>Удалить назначение операции</h2>
  <p>Вы уверены, что хотите удалить "{{ code.kroy.name }} - {{ code.operation_code.code }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-sm">Подтвердить</button>
    <a href="{% url 'main:kroy_operation_code_list' %}" class="btn btn-secondary btn-sm">Отменить</a>
  </form>
</div>
{% endblock %}

ulan/main/templates/main/opercode/kroy_operation_code_form.html
{% extends "main/base.html" %}

{% block content %}
<div class="container mt-2">
  <h2>{% if form.instance.pk %}Изменить{% else %}Создать{% endif %} назначение операции</h2>
  <form method="post" class="mt-3">
    {% csrf_token %}

    <div class="form-group row">
      <label for="kroy" class="col-md-3 col-form-label">{{ form.kroy.label }}</label>
      <div class="col-md-6">
        {{ form.kroy }}
        {% if form.kroy.errors %}
          <div class="invalid-feedback" id="kroy">
            {{ form.kroy.errors }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="form-group-sm row mt-2 ">
      <label for="operation_code" class="col-md-3 col-form-label">{{ form.operation_code.label }}</label>
      <div class="col-md-6">
        {{ form.operation_code }}
        {% if form.operation_code.errors %}
          <div class="invalid-feedback" id="operation_code">
            {{ form.operation_code.errors }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3">
        <label class="form-check-label" for="is_active">{{ form.is_active.label }}</label>
      </div>
      <div class="col-md-9" id="is_active">
        {{ form.is_active }}
        {% if form.is_active.errors %}
          <div class="invalid-feedback">
            {{ form.is_active.errors }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-9 offset-md-3">
        <button type="submit" class="btn btn-secondary btn-sm">Сохранить</button>
        <a href="{% url 'main:kroy_operation_code_list' %}" class="btn btn-secondary btn-sm ml-2">Назад в список</a>
      </div>
    </div>
  </form>
</div>
{% endblock %}

ulan/main/templates/main/opercode/kroy_operation_code_list.html
{% extends "main/base.html" %}
{% block content %}
<div class="container mt-2">
  <h2>Назначение операции</h2>
  <a href="{% url 'main:kroy_operation_code_create' %}" class="btn btn-secondary btn-sm mb-3">Создать новый</a>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Крой</th>
        <th scope="col">Код операции</th>
        <th scope="col">Действие</th>
      </tr>
    </thead>
    <tbody>
      {% for code in codes %}
      <tr>
        <td>{{ code.kroy.kroy_no }}</td>
        <td>{{ code.operation_code.title }}1</td>
        <td>
          <a href="{% url 'main:kroy_operation_code_edit' code.pk %}" class="btn btn-secondary btn-sm">Изменить</a>
          <a href="{% url 'main:kroy_operation_code_delete' code.pk %}" class="btn btn-danger btn-sm">Удалить</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

ulan/main/templates/main/opercode/kroy_operation_code_update.html
{% extends "main/base.html" %}

{% block content %}

<div class="container mt-2">
  <h2>{% if form.instance.pk %}Изменить{% else %}Создать{% endif %} назначение операции</h2>
  <form method="post" class="mt-3">
    {% csrf_token %}

    <div class="form-group row">
      <label for="kroy" class="col-md-3 col-form-label">{{ form.kroy.label }}</label>
      <div class="col-md-6">
        {{ form.kroy }}
        {% if form.kroy.errors %}
          <div class="invalid-feedback" id="kroy">
            {{ form.kroy.errors }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="form-group-sm row mt-2 ">
      <label for="operation_code" class="col-md-3 col-form-label">{{ form.operation_code.label }}</label>
      <div class="col-md-6">
        {{ form.operation_code }}
        {% if form.operation_code.errors %}
          <div class="invalid-feedback" id="operation_code">
            {{ form.operation_code.errors }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3">
        <label class="form-check-label" for="is_active">{{ form.is_active.label }}</label>
      </div>
      <div class="col-md-9" id="is_active">
        {{ form.is_active }}
        {% if form.is_active.errors %}
          <div class="invalid-feedback">
            {{ form.is_active.errors }}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-9 offset-md-3">
        <button type="submit" class="btn btn-secondary btn-sm">Сохранить</button>
        <a href="{% url 'main:kroy_operation_code_list' %}" class="btn btn-secondary btn-sm ml-2">Назад в список</a>
      </div>
    </div>
  </form>
</div>
{% endblock %}