ulan/account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [

    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),
    path('user-logout/', views.user_logout_request, name='user_logout'),
    path('masterdata_login/', views.masterdata_login, name='masterdata_login'),

]

ulan/client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns = [
    path('', views.client_list, name='client_list'),
    path('add/', views.client_add, name='client_add'),
    path('edit/<int:pk>/', views.client_edit, name='client_edit'),
    path('delete/<int:pk>/', views.client_delete, name='client_delete'),
]

ulan/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import (KroyListView, KroyCreateView, KroyUpdateView, KroyDetailListView, KroyDeleteView,
                    KroyDetailCreateView, KroyDetailUpdateView, MasterdataListView, masterdatauser,
                    operation_code_create, operation_code_update, operation_code_delete, KroyDetailView,
                    KroyDetailDeleteView, get_operation_codes, get_operation_list, users)
app_name = 'main'

urlpatterns = [
    #path("", views.index, name="home"),
    path("index", views.index),

    path('users/', users, name='users'),

    path('kroy/', KroyListView.as_view(), name='kroy-list'),
    path('kroy/create/', KroyCreateView.as_view(), name='kroy-create'),
    path('kroy/update/<int:pk>/', KroyUpdateView.as_view(), name='kroy-update'),
    path('kroy/delete/<int:pk>/', KroyDeleteView.as_view(), name='kroy-delete'),

    path('<int:kroy_id>/', views.KroyDetailView, name='kroy-detail-view'),
    path('kroy-detail/', KroyDetailListView.as_view(), name='kroy-detail-list'),
    path('kroy-detail/create/<int:kroy_id>', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    path('kroy-detail/update/<int:pk>/', KroyDetailUpdateView.as_view(), name='kroy-detail-update'),
    path('kroy-detail/delete/<int:pk>/', KroyDetailDeleteView.as_view(), name='kroy-detail-delete'),
    path('kroy-detail/<int:kroy_id>/', KroyDetailView, name='kroy-detail-view'),



    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),

    #path('kroy_details/new/<int:kroy_id>/', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),
    path('masterdata', MasterdataListView.as_view(), name='masterdata_list'),

    #Users page
    #path('main/masterdatauser/', views.masterdatauser_view, name='masterdatauser'),
    path('masterdatauser/', views.masterdatauser, name='masterdatauser'),
    path('get_operation_codes/', get_operation_codes, name='get_operation_codes'),
    path('get_operation_list/', get_operation_list, name='get_operation_list'),
    path('get_operation_price', views.get_operation_price, name='get_operation_price'),

    #Operations
    path('operation_code/create/', views.operation_code_create, name='operation_code_create'),
    path('operation_code/<int:pk>/update/', views.operation_code_update, name='operation_code_update'),
    path('operation_code/<int:pk>/delete/', views.operation_code_delete, name='operation_code_delete'),
    path('operation_code/', views.operation_code_list, name='operation_code_list'),

    path('operation_code/<int:operation_code_id>/operations/', views.operation_list_detail, name='operation_list_detail'),
    path('operation_code/<int:operation_code_id>/operations/create/', views.operation_list_create, name='operation_list_create'),
    path('operation_code/operations/<int:pk>/edit/', views.operation_list_update, name='operation_list_update'),
    path('operation_code/operations/<int:pk>/delete/', views.operation_list_delete, name='operation_list_delete'),
    path('operation-list/<int:operation_code_id>/', views.OperationListView, name='operation_list'),

    #kroy+operation naznachenie operatsii
    path('opercode/', views.kroy_operation_code_list, name='kroy_operation_code_list'),
    path('opercode/new/', views.kroy_operation_code_create, name='kroy_operation_code_create'),
    path('opercode/<int:pk>/edit/', views.kroy_operation_code_edit, name='kroy_operation_code_edit'),
    path('opercode/<int:pk>/delete/', views.kroy_operation_code_delete, name='kroy_operation_code_delete'),
]

ulan/material/urls.py
from django.urls import path
from . import views

app_name = 'material'

urlpatterns = [
    path('', views.malzeme_listesi, name='malzeme_listesi'),
    path('edit/<int:pk>/', views.malzeme_edit, name='malzeme_edit'),
    path('delete/<int:pk>/', views.malzeme_delete, name='malzeme_delete'),
    path('malzeme/<int:pk>/', views.malzeme_detayi, name='malzeme_detayi'),
    path('giris/', views.malzeme_giris, name='malzeme_giris'),
    path('cikis/', views.malzeme_cikis, name='malzeme_cikis'),
    path('kaydet/', views.malzeme_kaydet, name='malzeme_kaydet'),
]

ulan/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('add/', views.order_add, name='order_add'),
    path('edit/<int:pk>/', views.order_edit, name='order_edit'),
    path('delete/<int:pk>/', views.order_delete, name='order_delete'),
    path('orderitem_list/', views.orderitem_list, name='orderitem_list'),
    path('orderitem_list/<int:order_id>/', views.orderitem_list_by_order, name='orderitem_list_by_order'),
    path('item/add/<int:order_id>/', views.orderitem_add, name='orderitem_add'),
    path('item/edit/<int:pk>/', views.orderitem_edit, name='orderitem_edit'),
    path('item/delete/<int:pk>/', views.orderitem_delete, name='orderitem_delete'),
]

ulan/reports/urls.py
from django.urls import path
from . import views
from .views import weekly_report, weekly_report_all

app_name = 'reports'
urlpatterns = [
    path("", views.index, name="home"),
    path("index", views.index),
    path('weekly-report/', weekly_report, name='weekly_report'),
    path('weekly-report-all/', weekly_report_all, name='weekly_report_all'),
    path('report/', views.alluser_report, name='alluser_report'),
]

ulan/ulan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('reports.urls')),
    path('', include(('reports.urls', 'reports'), namespace='reports')),
    path('main/', include('main.urls')),
    path('account/', include('account.urls')),
    path('material/', include('material.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('orders/', include('orders.urls')),
    path('client/', include('client.urls')),
    #path('reports/', include('reports.urls', namespace='reports')),
 #   path('login/', LoginView.as_view(), name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ulan/reports/models.py
from django.db import models

# Create your models here.

ulan/reports/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from main.models import Status, Kroy

class ReportForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=User.objects.all(),
        label="Пользователь",
        required=False
    )
    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        label="Состояние работ",
        required=False
    )
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата начала')
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата окончания')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control form-control-sm'})


class Report_allForm(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.all(), required=False, label='Пользователь')
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата начала')
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата окончания')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control form-control-sm'})

class AlluserReportForm(forms.Form):
    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        required=False,
        label='Статус',
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    kroy_no = forms.ModelChoiceField(
        queryset=Kroy.objects.all(),
        required=False,
        label='Крой номер',
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата начала')
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата окончания')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control form-control-sm'})

ulan/reports/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.db.models import Sum
from main.models import Masterdata
from .forms import ReportForm, Report_allForm, AlluserReportForm

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect("account:login")
    return render(request, "reports/index.html")


def weekly_report(request):
    form = ReportForm()
    report_data = None
    user = None  # Kullanıcıyı burada başlatıyoruz
    status = None
    total_units = 0

    if request.method == "POST":
        form = ReportForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            status = form.cleaned_data['status']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']

            # Filtreleme
            report_data = Masterdata.objects.filter(
                created__range=(start_date, end_date),
                user=user if user else None,
                status=status if status else None
            )

            # Подсчет общей суммы единиц
            total_units = report_data.aggregate(total=Sum('edinitsa'))['total'] or 0

    return render(request, 'reports/weekly_report.html', {
        'form': form,
        'report_data': report_data,
        'user': user,  # Kullanıcıyı template'e gönderiyoruz
        'status': status,
        'total_units': total_units  # Добавляем общую сумму в контекст
    })

def weekly_report_all(request):
    form = Report_allForm()
    report_data = None
    user = None

    if request.method == "POST":
        form = Report_allForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data.get('user')
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')

            # Filtreleme
            if user:
                report_data = Masterdata.objects.filter(
                    created__range=(start_date, end_date),
                    user=user
                )
            else:
                report_data = Masterdata.objects.filter(
                    created__range=(start_date, end_date)
                )

    return render(request, 'reports/weekly_report_all.html', {
        'form': form,
        'report_data': report_data,
        'user': user,
    })

def alluser_report(request):
    form = AlluserReportForm(request.GET or None)
    report_data = []
    status = None
    kroy_no = None
    start_date = None
    end_date = None

    if request.method == 'GET' and form.is_valid():
        status = form.cleaned_data.get('status')
        kroy_no = form.cleaned_data.get('kroy_no')
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')

        filters = {}
        if status:
            filters['status'] = status
        if status:
            filters['kroy_no'] = kroy_no
        if start_date:
            filters['created__gte'] = start_date
        if end_date:
            filters['created__lte'] = end_date

        report_data = (
            Masterdata.objects
            .filter(**filters)
            .values('user__username', 'created', 'user__first_name', 'user__last_name')
            .annotate(total_edinitsa=Sum('edinitsa'), total_price=Sum('price'))
        )


    context = {
        'form': form,
        'report_data': report_data,
        'status': status,
        'kroy_no': kroy_no,
        'start_date': start_date,
        'end_date': end_date,
        #'created': created,
    }
    return render(request, 'reports/alluser_report.html', context)

ulan/reports/templates/reports/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- SheetJS Kütüphanesi--- to exel-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>

    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    {% block css_files %} {% endblock %}
    <title>{% block title %} {% endblock %} | Production</title>
</head>
<body>

{% include 'reports/partials/_nav_client.html' %}

<div class="container">
{% block content %}{% endblock %}
    </div>
<script src="{% static 'js/print.js' %}"></script>
<script src="{% static 'js/to_exel.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


{% block js_files %} {% endblock %}
</body>
</html>

ulan/reports/templates/reports/index.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">
<head>
<script src="{% static 'assets/js/color-modes.js' %}"></script>
<link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBogGzU1OgkYFZilHafgg+GYnTn0gjN15SbWkdZ3QKkR4NX9" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'reports/css/index_style.css' %}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
<link href="{% static 'main/css/dashboard.css' %}" rel="stylesheet">
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>T-Soft V 1</title>
</head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="#">T-Soft v 1</a>
  <ul class="navbar-nav flex-row d-md-none">
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle search">
        <i class="bi bi-search"></i>
      </button>
    </li>
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <i class="bi bi-list"></i>
      </button>
    </li>
  </ul>
  <div id="navbarSearch" class="navbar-search w-100 collapse">
    <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  </div>
</header>
<div class="container-fluid">
  <div class="row">
    <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
      <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="sidebarMenuLabel">T-Soft</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="#">
                <i class="bi bi-house-fill"></i>
                Главный панел
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'orders:order_list' %}">
                <i class="bi bi-file-earmark"></i>
                Заказы
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'main:kroy-list' %}">
                <i class="bi bi-building"></i>
                Производство
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'material:malzeme_listesi' %}">
                <i class="bi bi-cart"></i>
                Склад материалов
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'warehouse:product_list'%}">
                <i class="bi bi-cart"></i>
                Склад готовых продукт
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'client:client_list' %}">
                <i class="bi bi-people-fill"></i>
                Клиенты
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'reports:weekly_report' %}">
                <i class="bi bi-graph-up"></i>
                Отчеты
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-puzzle"></i>
                Интеграция
              </a>
            </li>
          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
            <span>Сохраненные отчеты</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
              <i class="bi bi-plus-circle"></i>
            </a>
          </h6>
          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'main:masterdata_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                Общая таблица
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-file-earmark-text"></i>
                Текущий месяц
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-file-earmark-text"></i>
                Последняя квартал
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-file-earmark-text"></i>
                Конце года - продажа
              </a>
            </li>
          </ul>

          <hr class="my-3">

          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="/admin/">
                <i class="bi bi-gear-wide-connected"></i>
                Настройки
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{%url 'account:logout'%}">
                <i class="bi bi-door-closed"></i>
                Выход
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Показатели</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Поделиться</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Экспорт</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
            <svg class="bi"><use xlink:href="#calendar3"/></svg>
            <a href="{% url 'reports:weekly_report' %}"> Текущая неделя</a>
          </button>
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          {% include 'reports/partials/indicator_shipment_lastweek.html' %}
          </div>
        <div class="col-6">
          {% include 'reports/partials/listorders_last_mount.html' %}
        </div>
        </div>
      <div class="row">
        <div class="col-2">

        </div>
      <div class="col-10">
        {% include 'reports/partials/production_weekly_report.html' %}
      </div>
      </div>
    </main>
  </div>
</div>
    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js" integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp" crossorigin="anonymous"></script>
    <script src="{% static 'main/js/dashboard.js' %}"></script>
  </body>
</html>