ulan/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import (KroyListView, KroyCreateView, KroyUpdateView, KroyDetailListView, KroyDeleteView,
                    KroyDetailCreateView, KroyDetailUpdateView, MasterdataListView, masterdatauser,
                    operation_code_create, operation_code_update, operation_code_delete, KroyDetailView,
                    KroyDetailDeleteView, get_operation_codes, get_operation_list, users)
app_name = 'main'

urlpatterns = [
    #path("", views.index, name="home"),
    path("index", views.index),

    path('users/', users, name='users'),

    path('kroy/', KroyListView.as_view(), name='kroy-list'),
    path('kroy/create/', KroyCreateView.as_view(), name='kroy-create'),
    path('kroy/update/<int:pk>/', KroyUpdateView.as_view(), name='kroy-update'),
    path('kroy/delete/<int:pk>/', KroyDeleteView.as_view(), name='kroy-delete'),

    path('<int:kroy_id>/', views.KroyDetailView, name='kroy-detail-view'),
    path('kroy-detail/', KroyDetailListView.as_view(), name='kroy-detail-list'),
    path('kroy-detail/create/<int:kroy_id>', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    path('kroy-detail/update/<int:pk>/', KroyDetailUpdateView.as_view(), name='kroy-detail-update'),
    path('kroy-detail/delete/<int:pk>/', KroyDetailDeleteView.as_view(), name='kroy-detail-delete'),
    path('kroy-detail/<int:kroy_id>/', KroyDetailView, name='kroy-detail-view'),



    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),

    #path('kroy_details/new/<int:kroy_id>/', KroyDetailCreateView.as_view(), name='kroy-detail-create'),
    #path('kroy_details/<int:pk>/', views.KroyDetailView, name='kroy-detail-view'),
    path('masterdata', MasterdataListView.as_view(), name='masterdata_list'),

    #Users page
    #path('main/masterdatauser/', views.masterdatauser_view, name='masterdatauser'),
    path('masterdatauser/', views.masterdatauser, name='masterdatauser'),
    path('get_operation_codes/', get_operation_codes, name='get_operation_codes'),
    path('get_operation_list/', get_operation_list, name='get_operation_list'),
    path('get_operation_price', views.get_operation_price, name='get_operation_price'),

    #Operations
    path('operation_code/create/', views.operation_code_create, name='operation_code_create'),
    path('operation_code/<int:pk>/update/', views.operation_code_update, name='operation_code_update'),
    path('operation_code/<int:pk>/delete/', views.operation_code_delete, name='operation_code_delete'),
    path('operation_code/', views.operation_code_list, name='operation_code_list'),

    path('operation_code/<int:operation_code_id>/operations/', views.operation_list_detail, name='operation_list_detail'),
    path('operation_code/<int:operation_code_id>/operations/create/', views.operation_list_create, name='operation_list_create'),
    path('operation_code/operations/<int:pk>/edit/', views.operation_list_update, name='operation_list_update'),
    path('operation_code/operations/<int:pk>/delete/', views.operation_list_delete, name='operation_list_delete'),
    path('operation-list/<int:operation_code_id>/', views.OperationListView, name='operation_list'),

    #kroy+operation naznachenie operatsii
    path('opercode/', views.kroy_operation_code_list, name='kroy_operation_code_list'),
    path('opercode/new/', views.kroy_operation_code_create, name='kroy_operation_code_create'),
    path('opercode/<int:pk>/edit/', views.kroy_operation_code_edit, name='kroy_operation_code_edit'),
    path('opercode/<int:pk>/delete/', views.kroy_operation_code_delete, name='kroy_operation_code_delete'),
]

ulan/ulan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('reports.urls')),
    path('', include(('reports.urls', 'reports'), namespace='reports')),
    path('main/', include('main.urls')),
    path('account/', include('account.urls')),
    path('material/', include('material.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('orders/', include('orders.urls')),
    path('client/', include('client.urls')),
    #path('reports/', include('reports.urls', namespace='reports')),
 #   path('login/', LoginView.as_view(), name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ulan/main/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.contrib.auth import get_user_model
from orders.models import Order
#from client.models import Client

def get_default_user():
    return get_user_model().objects.first()

class Product_type(models.Model):
    class Meta:
            verbose_name = ('Тип одежды')
            verbose_name_plural = ('Тип одежды')

    name = models.CharField(max_length=50, verbose_name='Название')
    def __str__(self):
        return self.name

class Operation_code(models.Model):
    class Meta:
        verbose_name_plural = ('Код оперции')

    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Примечение')
    product_type = models.ForeignKey(Product_type, on_delete=models.CASCADE, verbose_name='Тип одежды')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
        return self.title

class Operation_list(models.Model):
    class Meta:
        verbose_name_plural = ('Список оперции')

    title = models.CharField(max_length=50, verbose_name='Название')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    operation_code = models.ForeignKey(Operation_code, on_delete=models.CASCADE, verbose_name='Код оперции')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
        return self.title



class Kroy(models.Model):
    class Meta:
        verbose_name_plural = ('Крой')

    name = models.CharField(max_length=250, verbose_name='Наименование')
    kroy_no = models.CharField(max_length=20, verbose_name='Крой номер')
    ras_tkani = models.FloatField(verbose_name='Расход ткани')
    ras_dublerin = models.FloatField(verbose_name='Расход дублерин')
    edinitsa = models.IntegerField(null=True, blank=True, verbose_name='Единица')
    description = models.TextField(null=True, blank=True, verbose_name='Примечение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Заказ")

    def __str__(self):
        return str(self.kroy_no)

class Kroy_operation_code(models.Model):
    class Meta:
        verbose_name_plural = ('Применить операцию на крой')

    kroy = models.ForeignKey(Kroy, on_delete=models.CASCADE, verbose_name='Крой')
    operation_code = models.ForeignKey(Operation_code, on_delete=models.CASCADE, verbose_name='Код оперции')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
       return f"{self.kroy} - {self.operation_code}"

class City(models.Model):
    class Meta:
        verbose_name_plural = ('Города')
    name = models.CharField(max_length=100, verbose_name='Город')

    def __str__(self):
        return str(self.name)


class Colors(models.Model):
    class Meta:
        verbose_name_plural = ('Цвет кроя')
    name = models.CharField(max_length=100, verbose_name='Цвет')

    def __str__(self):
       return str(self.name)


class Kroy_detail(models.Model):

    class Meta:
            verbose_name_plural = ('Крой детально')
    kroy = models.ForeignKey(Kroy, on_delete=models.CASCADE, verbose_name='Крой')
    pachka = models.CharField(max_length=200, verbose_name='Пачка')
    razmer = models.CharField(max_length=200, verbose_name='Размер')
    rost = models.CharField(max_length=200, verbose_name='Рост')
    stuk = models.IntegerField(verbose_name='Штук')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    color = models.ForeignKey(Colors, on_delete=models.CASCADE, verbose_name='Цвет')
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Город')
    description = models.TextField(null=True, blank=True, verbose_name='Примечение')

    def __str__(self):
        return self.pachka

class Status(models.Model):
    class Meta:
            verbose_name_plural = ('Статус')

    name = models.CharField(max_length=50, verbose_name="Статус")
    def __str__(self):
       return str(self.name)

class Masterdata(models.Model):
    class Meta:
            verbose_name_plural = ('Общая таблица')

    status = models.ForeignKey(Status, on_delete=models.CASCADE, verbose_name='Статус' )
    kroy_no = models.ForeignKey(Kroy, on_delete=models.CASCADE, verbose_name='Крой номер')
    edinitsa = models.IntegerField(verbose_name='Единица')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    description = models.TextField(null=True, blank=True, verbose_name='Примечение')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    user_group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Группа пользователя')  # Yeni alan
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    confirmation = models.BooleanField(default=False, verbose_name='Подтверждение')
    operations = models.CharField(max_length=150, verbose_name='Операция')
    type_product = models.CharField(max_length=150, verbose_name='Тип одежды')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    operation_code = models.ForeignKey(Operation_code, on_delete=models.CASCADE, verbose_name='Код операции')

    def __str__(self):
        return f"{self.status} - {self.kroy_no}"

class Operations(models.Model):
    class Meta:
            verbose_name_plural = ('Операции')

    name = models.CharField(max_length=50, verbose_name='Наименование')
    price = models.IntegerField(verbose_name='Цена')
    kroy = models.ForeignKey(Kroy, on_delete=models.CASCADE, verbose_name='Крой')
    product_type = models.ForeignKey(Product_type, on_delete=models.CASCADE, verbose_name='Тип одежды')

    def total_price(self):
        return sum(self.objects.all().values_list('price', flat=True))

ulan/main/forms.py
from django import forms
from .models import Kroy, Kroy_detail, Masterdata, Operation_code, Operation_list, Kroy_operation_code  #, Code_operation, Kroy_operations
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

class KroyForm(forms.ModelForm):
    class Meta:
        model = Kroy
        fields = ['kroy_no', 'name', 'ras_tkani', 'ras_dublerin', 'order', 'edinitsa', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 23}),
        }

    def clean_kroy_no(self):
        kroy_no = self.cleaned_data.get('kroy_no')
        if self.instance and self.instance.pk is not None:
            return kroy_no
        if Kroy.objects.filter(kroy_no=kroy_no).exists():
            raise ValidationError("Этот номер Кроя уже существует. Пожалуйста, введите другой номер.")
        return kroy_no

class KroyDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.kroy_instance = kwargs.pop('kroy_instance', None)
        super(KroyDetailForm, self).__init__(*args, **kwargs)
        if self.kroy_instance:
            self.fields['kroy'].widget.attrs['readonly'] = True
            self.initial['kroy'] = self.kroy_instance.pk

    class Meta:
        model = Kroy_detail
        fields = ['kroy', 'pachka', 'razmer', 'rost', 'stuk', 'city', 'color','description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 23}),
        }

class MasterdataSearchForm(forms.Form):
    start_date = forms.DateField(label='Дата начала', required=False)
    end_date = forms.DateField(label='Дата окончания', required=False)
    uchastok_search = forms.CharField(label='Искать по участке', required=False)
    kroy_no_search = forms.CharField(label='Искать по крой но:', required=False)
    user = forms.CharField(label='Искать по крой но:', required=False)

class MasterdataForm(forms.ModelForm):
    class Meta:
        model = Masterdata
        fields = ['user']  # Add other fields as needed

class OperationCodeForm(forms.ModelForm):
    class Meta:
        model = Operation_code
        fields = ['title', 'description', 'product_type', 'is_active']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 23}),
        }

class OperationListForm(forms.ModelForm):
    class Meta:
        model = Operation_list
        fields = ['title', 'price']

class KroyOperationCodeForm(forms.ModelForm):
    class Meta:
        model = Kroy_operation_code
        fields = ['kroy', 'operation_code', 'is_active']
        widgets = {
            'kroy': forms.Select(attrs={'class': 'form-control'}),
            'operation_code': forms.Select(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

ulan/main/templates/main/kroy/_nav_kroy.html
<a href="{% url 'main:kroy-create' %}" class="btn btn-secondary btn-sm" >Создать новый Крой</a>

ulan/main/templates/main/kroy/kroy_confirm_delete.html
{% extends "main/base.html" %}

{% block content %}
<div class="container">
    <h4>Удалить Крой</h4>
    <p>Вы уверены, что хотите удалить "{{ object.kroy_no }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'main:kroy-list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

ulan/main/templates/main/kroy/kroy_detail_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Подтвердить удаление{% endblock %}

{% block content %}
<div class="container mt-5">
    <h4>Вы уверены, что хотите удалить эту пачку?</h4>
    <form method="post">{% csrf_token %}
        <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
        <a href="{% url 'main:kroy-detail-list' %}" class="btn btn-secondary btn-sm">Отмена</a>
    </form>
</div>
{% endblock %}

ulan/main/templates/main/kroy/kroy_detail_form.html
{% extends "main/base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %} Создать новую крой деталь {% endblock %}

{% block content %}
<div class="container mt-2">

    <h2>Создать новую крой деталь</h2>
    <form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}

    <div class="form-group" style="display: none;">
        <label for="{{ form.kroy.id_for_label }}">Крой</label>
        <div class="ml-2" id="{{ form.kroy.id_for_label }}">{{ form.kroy }}</div>
    </div>

    <div class="form-group">
        <label for="{{ form.pachka.id_for_label }}">Пачка</label>
        <div class="ml-2" id="{{ form.pachka.id_for_label }}">{{ form.pachka }}</div>
    </div>

    <div class="form-group">
        <label for="{{ form.razmer.id_for_label }}">Размер</label>
        <div class="ml-2" id="{{ form.razmer.id_for_label }}">{{ form.razmer }}</div>
    </div>

    <div class="form-group">
        <div class="ml-2"><label for="{{ form.rost.id_for_label }}">Рост</label>
        <div class="ml-2" id="{{ form.rost.id_for_label }}">{{ form.rost }}</div>
    </div>

    <div class="form-group">
        <label for="{{ form.stuk.id_for_label }}">Штук</label>
        <div class="ml-2" id="{{ form.stuk.id_for_label }}">{{ form.stuk }}</div>
    </div>

    <div class="form-group">
        <label for="{{ form.city.id_for_label }}">Город</label>
        <div class="ml-2" id="{{ form.city.id_for_label }}">{{ form.city }}</div>
    </div>

    <div class="form-group">
        <label for="1">Цвет</label>
        <div class="ml-2" id="1">{{ form.color }}</div>
    </div>

        <div class="form-group">
        <label for="{{ form.description.id_for_label }}">Примичение:</label>
        <div class="ml-2" id="{{ form.description.id_for_label }}">{{ form.description }}</div>
    </div>

<button type="submit" class="btn btn-secondary mt-2 btn-sm">Сохранить</button>
    </div>
</form>

</div>
{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>
{% endblock %}

ulan/main/templates/main/kroy/kroy_detail_list.html
{% extends "main/base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %} Список крой детали {% endblock %}

{% block content %}
<div class="container">
    {% include 'main/kroy/_nav_kroy.html' %}

     <table class="table caption-top">
  <caption>Список последний 30 добавленных деталей</caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Крой №</th>
      <th scope="col">Пачка</th>
      <th scope="col">Размер</th>
      <th scope="col">Рост</th>
      <th scope="col">Штук</th>
      <th scope="col">Цвет</th>
      <th scope="col">Город</th>
      <th scope="col"> </th>
    </tr>
  </thead>

  <tbody>
     {% for kroy_detail in latest_kroys %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ kroy_detail.kroy }}</td>
      <td>{{ kroy_detail.pachka }}</td>
      <td>{{ kroy_detail.razmer }}</td>
      <td>{{ kroy_detail.rost }}</td>
      <td>{{ kroy_detail.stuk }}</td>
      <td>{{ kroy_detail.color }}</td>
      <td>{{ kroy_detail.city }}</td>
      <td> <a href="{% url 'main:kroy-detail-update' kroy_detail.pk %}" >изменить</a></td>
    </tr>
     {% empty %}
        <tr>
            <td colspan="9">Нет доступных позиций.</td>
        </tr>
     {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>
{% endblock %}

ulan/main/templates/main/kroy/kroy_detail_view.html
{% extends "main/base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %}
{% if form.instance.pk %}
Изменить крой
{% else %}
Создать Кроя
{% endif %}
{% endblock %}

{% block content %}
<div class="container mt-2">
{% include 'partials/print.html' %}
<a href="{% url 'main:kroy-detail-create' kroy_instance.pk %}" class="btn btn-primary btn-sm mt-2">Создать крой детали</a>
    <div id="table-container" class="">
        <div class="container mt-2">
Операции:
            {% for code in kroy_operation_codes %}
            <a href="{% url 'main:operation_list' code.operation_code.id %}">
                {{ forloop.counter }}. {{ code.operation_code }} - {{ code.operation_code.product_type.name }}
            </a>
            {% endfor %}
        </div>

        <h4 class="mt-2"> Крой № {{ kroy_instance.kroy_no }} -- {{ kroy_instance.name }}</h4>
        <p><strong> Дата создания:</strong> {{ kroy_instance.created }}, <strong>Расход ткани:</strong> {{ kroy_instance.ras_tkani }},
            <strong>Расход дублерин:</strong> {{ kroy_instance.ras_dublerin }},
            <strong>Единица:</strong> {{ stuk_total }}</p>
        <p><strong>Примечение:</strong> {{ kroy_instance.description }}</p>


        <table class="table table-striped">
            <thead class="table-light">
                <tr>

                    <th scope="col">Пачка</th>
                    <th scope="col">Размер</th>
                    <th scope="col">Рост</th>
                    <th scope="col">Штук</th>
                    <th scope="col">Цвет</th>
                    <th scope="col">Город</th>
                    <th scope="col">Примечание:</th>
                    <th scope="col"></th>
                    <th scope="col"></th>

                </tr>
            </thead>

            <tbody>
                {% for detail in kroy_details %}
                <tr>
                    <!-- sadece small-row sınıfı kullanılıyor -->

                    <td>{{ detail.pachka }}</td>
                    <td>{{ detail.razmer }}</td>
                    <td>{{ detail.rost }}</td>
                    <td>{{ detail.stuk }}</td>
                    <td>{{ detail.color }}</td>
                    <td>{{ detail.city }}</td>
                    <td>{{ detail.description }}</td>
                    <td> <a href="{% url 'main:kroy-detail-update' detail.pk %}" class="btn btn-secondary btn-sm" >Изменить</a></td>

                    <td><a href="{% url 'main:kroy-detail-delete' detail.pk %}"  class="btn btn-danger btn-sm">Удалит</a></td>

                </tr>
                {% empty %}
                <tr>
                    <td colspan="9">Нет доступных позиций.</td>
                    <!-- Tüm sütunları kaplayan bir hücre eklendi -->
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/printTable.js' %}"></script>
{% endblock %}

ulan/main/templates/main/kroy/kroy_form.html
{% extends "main/base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %} {% if form.instance.pk %}Изменить крой{% else %}Создать Кроя{% endif %} {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h4>{% if form.instance.pk %}Изменить крой{% else %}Создать новый крой{% endif %}</h4>
            {% include 'main/kroy/_nav_kroy.html' %}

            <form method="post" class="mt-4">
    {% csrf_token %}
    {% if form.kroy_no.errors %}
        <div class="alert alert-danger">
            {% for error in form.kroy_no.errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.kroy_no.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.kroy_no }}</div>
    </div>
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.name.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.name }}</div>
    </div>
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.ras_tkani.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.ras_tkani }}</div>
    </div>
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.ras_dublerin.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.ras_dublerin }}</div>
    </div>

                <div class="row mt-2 ">
        <div class="col-md-4">{{ form.order.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.order }}</div>
    </div>
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.edinitsa.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.edinitsa }}</div>
    </div>
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.code_operations.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.code_operations }}</div>
    </div>
    <div class="row mt-2 ">
        <div class="col-md-4">{{ form.description.label_tag }}</div>
        <div class="col-6 col-md-3">{{ form.description }}</div>
    </div>
    <button type="submit" class="btn btn-secondary btn-sm mt-2">Сохранить</button>
</form>
        </div>
        <div class="col-md-8">
            <table class="table">
                <tr>
                    <th >#</th>
                    <th>Крой №</th>
                    <th></th>
                    <th>На.ание</th>
                    <th>Дата созд.</th>
                    <th>ед.ца</th>
                    <th>р.ткани</th>
                    <th>р.дублрн</th>
                </tr>
                <tbody>
                {% for kroy in kroy_list %}
                {% if kroy_no is active %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url 'main:kroy-detail-view' kroy.pk %}" >{{ kroy.kroy_no }}</a>
                    <td></td>
                    <td>{{ kroy.name|slice:":20" }}</td>
                    <td>{{ kroy.created|date:"d.m.Y" }}</td>
                    <td>{{ kroy.edinitsa }}</td>
                    <td>{{ kroy.ras_tkani }}</td>
                    <td>{{ kroy.ras_dublerin }} </td>
                    <td>{{ kroy.code_operations }} </td>

                    <td><a href="{% url 'main:kroy-update' kroy.pk %}" class="btn btn-secondary btn-sm" >Изменить</a></td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}
{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>
{% endblock %}

ulan/main/templates/main/kroy/kroy_list.html
{% extends "main/base.html" %}

{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}
{% block title %} Крой Список {% endblock %}

{% block content %}

<div class="container mt-2" id="table-container">
{% include 'partials/print.html' %}
<h4 class="mt-1">Крой Список</h4>
    <table class="table table-striped" >

        <thead class="table-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Крой №</th>
            <th scope="col"></th>
            <th scope="col">Наименование</th>
            <th scope="col">Дата создание</th>
            <th scope="col">Заказ</th>
            <th scope="col">Единица</th>
            <th>Изменить</th>
            <th>Удалит</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for kroy in object_list %}
        {% if kroy.is_active %}

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'main:kroy-detail-view' kroy.pk %}" >{{ kroy.kroy_no }}</a></td>
                <td></td>
                <td>{{ kroy.name|slice:":30" }}</td>
                <td>{{ kroy.created|date:"d.m.Y H:i" }}</td>

                <td>{{ kroy.order.orderno }} - {{ kroy.order.client }}</td>

                <td>{{ kroy.edinitsa }}</td>
                <td><a href="{% url 'main:kroy-update' kroy.pk %}" class="btn btn-secondary btn-sm">Изменить</a></td>
                <td>
                    <form method="post" action="{% url 'main:kroy-delete' kroy.pk %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Вы уверены, что хотите удалить этот элемент?');">Удалить</button>
                    </form>
                </td>
                <td></td>
                <td></td>
            </tr>

        {% endif %}
        {% empty %}
        <tr>
            <td colspan="10">В системе нет активного кроя</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>
{% endblock %}

ulan/main/templates/main/kroy/kroy_operations_list.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
{% endblock %}

{% block title %} Operations list {% endblock %}

{% block content %}

<div class="container mt-2">

    <h4>Операции крой {{ kroy_instance }}</h4>
    <table class=" table table-sm caption-top w-auto h-auto">
        <thead class="table-light">
            <tr>
                <th>Операция</th>
                <th>Цена</th>
            </tr>
        </thead>
        <tbody>
            {% for operation in kroy_operations %}
            <tr>
                <td>{{ operation.name }}</td>
                <td>{{ operation.price }} сом</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block js_files %}
<script src="{% static 'main/js/script.js' %}"></script>
{% endblock %}